package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtAssets generated by hbm2java
 */

@Entity
@Table(name="assets")
public class Assets  implements java.io.Serializable {


	private static final long serialVersionUID = -1675973826564936224L;
	@Id
	@GeneratedValue
	private Long id;
	private String viewableType;
	private Integer viewableId;
	private Integer attachmentWidth;
	private Integer attachmentHeight;
	private Integer attachmentFileSize;
	private Integer position;
	private String attachmentContentTtype;
	private String attachmentFileName;
	private String ttype;
	private Date attachmentUpdatedAt;
	private String alt;
	private Date createdAt;
	private Date updatedAt;
	private Integer digitalAssetId;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getViewableType() {
		return viewableType;
	}

	public void setViewableType(String viewableType) {
		this.viewableType = viewableType;
	}

	public Integer getViewableId() {
		return this.viewableId;
	}

	public void setViewableId(Integer viewableId) {
		this.viewableId = viewableId;
	}
	public Integer getAttachmentWidth() {
		return this.attachmentWidth;
	}

	public void setAttachmentWidth(Integer attachmentWidth) {
		this.attachmentWidth = attachmentWidth;
	}
	public Integer getAttachmentHeight() {
		return this.attachmentHeight;
	}

	public void setAttachmentHeight(Integer attachmentHeight) {
		this.attachmentHeight = attachmentHeight;
	}
	public Integer getAttachmentFileSize() {
		return this.attachmentFileSize;
	}

	public void setAttachmentFileSize(Integer attachmentFileSize) {
		this.attachmentFileSize = attachmentFileSize;
	}
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
	public String getAttachmentContentTtype() {
		return this.attachmentContentTtype;
	}

	public void setAttachmentContentTtype(String attachmentContentTtype) {
		this.attachmentContentTtype = attachmentContentTtype;
	}
	public String getAttachmentFileName() {
		return this.attachmentFileName;
	}

	public void setAttachmentFileName(String attachmentFileName) {
		this.attachmentFileName = attachmentFileName;
	}
	public String getTtype() {
		return this.ttype;
	}

	public void setTtype(String ttype) {
		this.ttype = ttype;
	}
	public Date getAttachmentUpdatedAt() {
		return this.attachmentUpdatedAt;
	}

	public void setAttachmentUpdatedAt(Date attachmentUpdatedAt) {
		this.attachmentUpdatedAt = attachmentUpdatedAt;
	}
	public String getAlt() {
		return this.alt;
	}

	public void setAlt(String alt) {
		this.alt = alt;
	}
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Integer getDigitalAssetId() {
		return this.digitalAssetId;
	}

	public void setDigitalAssetId(Integer digitalAssetId) {
		this.digitalAssetId = digitalAssetId;
	}




}


