package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtOptionTtypes generated by hbm2java
 */
@Entity
@Table(name="option_types")
public class OptionTypes  implements java.io.Serializable {


	/**
	 * 
	 * EXAMPLE- 
	 * 
	 * id |    name     | Presentation 
	 * 
	 * 1  | TShirt Size | Size
	 * 2  | TSHIRT Color| Color
	 * 
	 * 
	 */
	private static final long serialVersionUID = 7131035671602034411L;
	
	@Id
	@GeneratedValue
	private Long id;
	private String name;
	private String presentation;
	private int position;
	private Date createdAt;
	private Date updatedAt;

	public OptionTypes() {
	}


	public OptionTypes(int position) {
		this.position = position;
	}
	public OptionTypes(String name, String presentation, int position, Date createdAt, Date updatedAt) {
		this.name = name;
		this.presentation = presentation;
		this.position = position;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getPresentation() {
		return this.presentation;
	}

	public void setPresentation(String presentation) {
		this.presentation = presentation;
	}
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}




}


