package com.detalogic.model;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final



/**
 * DtOptionValueVariants generated by hbm2java
 */
@Entity
@Table(name="option_value_variants_mapping")
public class OptionValueVariants  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 4250089902854929700L;


	@Id
	@GeneratedValue
	private Long id;
	@ManyToOne(cascade = CascadeType.ALL)
	private Variants variant;
	@ManyToOne(cascade = CascadeType.ALL)
	private OptionValues optionValue;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Variants getVariant() {
		return variant;
	}
	public void setVariant(Variants variant) {
		this.variant = variant;
	}
	public OptionValues getOptionValue() {
		return optionValue;
	}
	public void setOptionValue(OptionValues optionValue) {
		this.optionValue = optionValue;
	}







}


