package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtProducts generated by hbm2java
 */

@Entity
@Table(name="product")
public class Product  implements java.io.Serializable {

	 /**
	 * 
	 */
	private static final long serialVersionUID = 6216313248836941676L;
	
	 @Id
	 @GeneratedValue(strategy=GenerationType.AUTO)
     private Long id;
     private String name;
     private String description;
     private Date availableOn;
     private Date deletedAt;
     private String slug;
     private String metaDescription;
     private String metaTkeywords;
     private Date createdAt;
     private Date updatedAt;
     private Boolean promotionable;
     private String metaTitle;
     private Date discontinueOn;
     private Integer favoriteUsersCount;
     private BigDecimal avgRating;
     private int reviewsCount;
     
//     @OneToMany(mappedBy = "product")
//     private Set<ProductsTaxons> productTaxons = new HashSet<>(0);


    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getAvailableOn() {
        return this.availableOn;
    }
    
    public void setAvailableOn(Date availableOn) {
        this.availableOn = availableOn;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }
    public String getMetaDescription() {
        return this.metaDescription;
    }
    
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }
    public String getMetaTkeywords() {
        return this.metaTkeywords;
    }
    
    public void setMetaTkeywords(String metaTkeywords) {
        this.metaTkeywords = metaTkeywords;
    }
 
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Boolean getPromotionable() {
        return this.promotionable;
    }
    
    public void setPromotionable(Boolean promotionable) {
        this.promotionable = promotionable;
    }
    public String getMetaTitle() {
        return this.metaTitle;
    }
    
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }
    public Date getDiscontinueOn() {
        return this.discontinueOn;
    }
    
    public void setDiscontinueOn(Date discontinueOn) {
        this.discontinueOn = discontinueOn;
    }
    public Integer getFavoriteUsersCount() {
        return this.favoriteUsersCount;
    }
    
    public void setFavoriteUsersCount(Integer favoriteUsersCount) {
        this.favoriteUsersCount = favoriteUsersCount;
    }
    public BigDecimal getAvgRating() {
        return this.avgRating;
    }
    
    public void setAvgRating(BigDecimal avgRating) {
        this.avgRating = avgRating;
    }
    public int getReviewsCount() {
        return this.reviewsCount;
    }
    
    public void setReviewsCount(int reviewsCount) {
        this.reviewsCount = reviewsCount;
    }

//
//	public Set<ProductsTaxons> getProductTaxons() {
//		return productTaxons;
//	}
//
//
//	public void setProductTaxons(Set<ProductsTaxons> productTaxons) {
//		this.productTaxons = productTaxons;
//	}


	




}


