package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtProtottypes generated by hbm2java
 */
@Entity
@Table(name="prototypes")
public class Prototypes  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4968230417952421592L;
	@Id
	private Long id;
     private String name;
     private Date createdAt;
     private Date updatedAt;

    public Prototypes() {
    }

    public Prototypes(String name, Date createdAt, Date updatedAt) {
       this.name = name;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


