package com.detalogic.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final



/**
 * DtProtottypeTaxons generated by hbm2java
 */
@Entity
@Table(name="property_taxon_mapping")
public class PrototypeTaxons  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8399085356052492381L;
	@Id
	@GeneratedValue
	private Long id;
    private Integer taxonId;
    private Integer protottypeId;

    public PrototypeTaxons() {
    }

    public PrototypeTaxons(Integer taxonId, Integer protottypeId) {
       this.taxonId = taxonId;
       this.protottypeId = protottypeId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getTaxonId() {
        return this.taxonId;
    }
    
    public void setTaxonId(Integer taxonId) {
        this.taxonId = taxonId;
    }
    public Integer getProtottypeId() {
        return this.protottypeId;
    }
    
    public void setProtottypeId(Integer protottypeId) {
        this.protottypeId = protottypeId;
    }




}


