package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DtTaxons generated by hbm2java
 */
@Entity
@Table(name="taxon")
public class Taxon  implements java.io.Serializable {


	private static final long serialVersionUID = 4709133037353510927L;
	@Id
	@GeneratedValue
	private Long id;
	private Integer position;
	private String name;
	private String permalink;
	private Integer lft;
	private Integer rgt;
	private String description;
	private Date createdAt;
	private Date updatedAt;
	private String metaTitle;
	private String metaDescription;
	private String metaTkeywords;
	private Integer depth;
	@OneToMany(mappedBy = "dtTaxons")
	private Set<ProductsTaxons> productTaxons = new HashSet<>(0);
	
	@ManyToOne(cascade={CascadeType.ALL})
	@JoinColumn(name="taxonomyId")
	private Taxon taxon;

	@OneToMany(mappedBy="taxon")
	private Set<Taxon> taxons = new HashSet<Taxon>();

	
	public Taxon() {
	}


	public Taxon(String name) {
		this.name = name;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getPermalink() {
		return this.permalink;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}
	
	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}
	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}
	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}
	public String getMetaTkeywords() {
		return this.metaTkeywords;
	}

	public void setMetaTkeywords(String metaTkeywords) {
		this.metaTkeywords = metaTkeywords;
	}
	public Integer getDepth() {
		return this.depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	public Set<ProductsTaxons> getProductTaxons() {
		return productTaxons;
	}

	public void setProductTaxons(Set<ProductsTaxons> productTaxons) {
		this.productTaxons = productTaxons;
	}

	public Taxon getTaxon() {
		return taxon;
	}

	public void setTaxon(Taxon taxon) {
		this.taxon = taxon;
	}


	public Set<Taxon> getTaxons() {
		return taxons;
	}


	public void setTaxons(Set<Taxon> taxons) {
		this.taxons = taxons;
	}


}


