package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DtTaxonomies generated by hbm2java
 */
@Entity
@Table(name="taxonomies")
public class Taxonomies  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 5559477399570681838L;
	@Id
	@GeneratedValue
	private Long id;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Integer position;
	
	@OneToMany(mappedBy="taxons")
	private Set<Taxon> taxons = new HashSet<Taxon>();


	public Taxonomies() {
	}


	public Taxonomies(String name) {
		this.name = name;
	}
	public Taxonomies(String name, Date createdAt, Date updatedAt, Integer position) {
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.position = position;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Set<Taxon> getTaxons() {
		return taxons;
	}


	public void setTaxons(Set<Taxon> taxons) {
		this.taxons = taxons;
	}


	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}




}


