package com.detalogic.model;
// Generated 17 Jul, 2018 4:21:04 PM by Hibernate Tools 4.3.5.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DtVariants generated by hbm2java
 */

@Entity
@Table(name="variants")
public class Variants  implements java.io.Serializable {


	/**
	 * 
	 */

	private static final long serialVersionUID = 1187649339828291045L;
	
	@Id
	@GeneratedValue
	private Long id;
	private String sku;
	private BigDecimal weight;
	private BigDecimal height;
	private BigDecimal width;
	private BigDecimal depth;
	private Date deletedAt;
	private Boolean isMaster;
	@ManyToOne
	@JoinColumn(name="product_id")
	private Product product;
	private BigDecimal costPrice;
	private Integer position;
	private String costCurrency;
	private Boolean trackInventory;
	private Integer taxCategoryId;
	private Date updatedAt;
	private Date discontinueOn;
	private Date createdAt;
	private Integer favoriteUsersCount;



	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}
	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}
	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}
	public BigDecimal getDepth() {
		return this.depth;
	}

	public void setDepth(BigDecimal depth) {
		this.depth = depth;
	}
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}
	public Boolean getIsMaster() {
		return this.isMaster;
	}

	public void setIsMaster(Boolean isMaster) {
		this.isMaster = isMaster;
	}

	public Product getProduct() {
		return product;
	}


	public void setProduct(Product product) {
		this.product = product;
	}


	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}
	public String getCostCurrency() {
		return this.costCurrency;
	}

	public void setCostCurrency(String costCurrency) {
		this.costCurrency = costCurrency;
	}
	public Boolean getTrackInventory() {
		return this.trackInventory;
	}

	public void setTrackInventory(Boolean trackInventory) {
		this.trackInventory = trackInventory;
	}
	public Integer getTaxCategoryId() {
		return this.taxCategoryId;
	}

	public void setTaxCategoryId(Integer taxCategoryId) {
		this.taxCategoryId = taxCategoryId;
	}
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Date getDiscontinueOn() {
		return this.discontinueOn;
	}

	public void setDiscontinueOn(Date discontinueOn) {
		this.discontinueOn = discontinueOn;
	}
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Integer getFavoriteUsersCount() {
		return this.favoriteUsersCount;
	}

	public void setFavoriteUsersCount(Integer favoriteUsersCount) {
		this.favoriteUsersCount = favoriteUsersCount;
	}




}


